#!/usr/bin/env bash
set -euo pipefail
mode="${1:-self-test}"
node --input-type=module - "$mode" <<'NODE'
import http from 'node:http';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { createHash, randomUUID } from 'node:crypto';
const mode=process.argv[2]??'self-test';
const tenants=new Map(); const idempotency=new Map();
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
function auth(req){const tenant=req.headers['x-tenant-id'];const user=req.headers['x-user-id'];if(typeof tenant!=='string'||typeof user!=='string')throw Object.assign(Error('missing tenant/user'),{status:401});return{tenant,user};}
function tasksFor(t){if(!tenants.has(t))tenants.set(t,new Map());return tenants.get(t);}
async function body(req){let raw='';for await(const c of req)raw+=c;if(raw.length>64*1024)throw Object.assign(Error('body too large'),{status:413});return raw?JSON.parse(raw):{};}
function json(res,status,data,headers={}){res.writeHead(status,{'content-type':'application/json; charset=utf-8','x-content-type-options':'nosniff',...headers});res.end(status===204?'':JSON.stringify(data));}
const server=http.createServer(async(req,res)=>{const started=Date.now();try{const {tenant,user}=auth(req);const store=tasksFor(tenant);if(req.method==='GET'&&req.url==='/health')return json(res,200,{ok:true});if(req.method==='GET'&&req.url==='/tasks')return json(res,200,{items:[...store.values()]});if(req.method==='POST'&&req.url==='/tasks'){const payload=await body(req);if(typeof payload.title!=='string'||!payload.title.trim())throw Object.assign(Error('title required'),{status:422});const key=req.headers['idempotency-key'];const fp=hash(payload);if(typeof key==='string'&&idempotency.has(`${tenant}:${key}`)){const previous=idempotency.get(`${tenant}:${key}`);if(previous.fingerprint!==fp)throw Object.assign(Error('idempotency conflict'),{status:409});return json(res,200,previous.task);}const task={id:randomUUID(),tenantId:tenant,title:payload.title.trim(),completed:false,createdBy:user,version:1};store.set(task.id,task);if(typeof key==='string')idempotency.set(`${tenant}:${key}`,{fingerprint:fp,task});return json(res,201,task,{location:`/tasks/${task.id}`});}const match=/^\/tasks\/([^/]+)$/.exec(req.url??'');if(match&&req.method==='PATCH'){const task=store.get(match[1]);if(!task)throw Object.assign(Error('not found'),{status:404});const payload=await body(req);if(typeof payload.completed==='boolean')task.completed=payload.completed;if(typeof payload.title==='string'&&payload.title.trim())task.title=payload.title.trim();task.version++;return json(res,200,task);}if(match&&req.method==='DELETE'){if(!store.delete(match[1]))throw Object.assign(Error('not found'),{status:404});return json(res,204,null);}throw Object.assign(Error('not found'),{status:404});}catch(e){json(res,e.status??500,{error:e.message});}finally{console.error(JSON.stringify({method:req.method,path:req.url,status:res.statusCode,durationMs:Date.now()-started}));}});
if(mode==='serve'){const port=Number(process.env.PORT??3000);server.listen(port,'127.0.0.1',()=>console.log(`task-saas listening on http://127.0.0.1:${port}`));}else{server.listen(0,'127.0.0.1');await once(server,'listening');const {port}=server.address();const call=(tenant,path,init={})=>fetch(`http://127.0.0.1:${port}${path}`,{...init,headers:{'x-tenant-id':tenant,'x-user-id':'u1','content-type':'application/json',...(init.headers??{})}});const created=await call('t1','/tasks',{method:'POST',headers:{'idempotency-key':'k1'},body:JSON.stringify({title:'Ship handbook'})});assert.equal(created.status,201);const task=await created.json();const replay=await call('t1','/tasks',{method:'POST',headers:{'idempotency-key':'k1'},body:JSON.stringify({title:'Ship handbook'})});assert.equal((await replay.json()).id,task.id);assert.equal((await(await call('t2','/tasks')).json()).items.length,0);const patched=await call('t1',`/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify({completed:true})});assert.equal((await patched.json()).completed,true);assert.equal((await call('t1',`/tasks/${task.id}`,{method:'DELETE'})).status,204);console.log(JSON.stringify({ok:true,tenantIsolation:true,idempotency:true,crud:true}));server.close();await once(server,'close');}
NODE
