import test from'node:test';import assert from'node:assert/strict';import{Email,Money,Password}from'./value-objects.solution.js';import{InMemoryUserRepository,userId}from'./repository.solution.js';import{Order}from'./aggregate.solution.js';import{buildApplication}from'./clean-arch/solution/main.js';
test('value objects enforce invariants',()=>{assert.equal(Email.create(' A@EXAMPLE.COM ').value,'a@example.com');assert.throws(()=>Email.create('bad'));assert.equal(Money.create(100,'JPY').add(Money.create(50,'JPY')).amount,150);assert.throws(()=>Money.create(1,'JPY').add(Money.create(1,'USD')));const p=Password.create('Strong-Pass-123!');assert.equal(p.verify('Strong-Pass-123!'),true);});
test('repository clones entities',async()=>{const r=new InMemoryUserRepository(),id=userId('u1');await r.save({id,name:'A',version:1});const u=await r.findById(id);u!.name='B';assert.equal((await r.findById(id))!.name,'A');});
test('aggregate enforces boundary and emits event',()=>{const o=Order.create({customerId:'c1'});o.addItem({productId:'p',quantity:2,price:Money.create(100,'JPY')});o.submit();assert.equal(o.total().amount,200);assert.equal(o.pullEvents()[0]!.type,'OrderSubmitted');assert.deepEqual(o.pullEvents(),[]);assert.throws(()=>o.addItem({productId:'x',quantity:1,price:Money.create(1,'JPY')}));});
test('clean architecture controller maps errors',async()=>{const app=buildApplication();const created=await app.controller.create({title:' task '});assert.equal(created.status,201);const id=(created.body as any).id;assert.equal((await app.controller.complete(id)).status,200);assert.equal((await app.controller.complete('missing')).status,404);});
import{auditSpec,buildInvitationSpec,createInvitationService,runAcceptanceChecks,TRANSITIONS}from'./spec-to-tests/solution/main.js';
test('spec drives acceptance checks',()=>{const spec=buildInvitationSpec();const report=runAcceptanceChecks(spec,createInvitationService);assert.equal(report.passed,report.total,report.results.filter(r=>!r.passed).map(r=>`${r.id}: ${r.failures.join(', ')}`).join(' | '));const audit=auditSpec(spec,report);assert.equal(audit.uncoveredRules.length,0,`例が紐づかないルール: ${audit.uncoveredRules.join(',')}`);assert.equal(audit.missingTransitions.length,0,`遷移表の空欄: ${audit.missingTransitions.join(',')}`);assert.equal(audit.unexercisedStatuses.length,0,`検証されない契約ステータス: ${audit.unexercisedStatuses.join(',')}`);assert.equal(audit.undeclaredStatuses.length,0,`契約にないステータス: ${audit.undeclaredStatuses.join(',')}`);});
test('breaking one rule fails only its examples',()=>{const spec=buildInvitationSpec();const broken=(o:Parameters<typeof createInvitationService>[0])=>createInvitationService({...o,ttlDays:14});const report=runAcceptanceChecks(spec,broken);const failed=report.results.filter(r=>!r.passed).map(r=>r.id).sort();assert.deepEqual(failed,['E-01','E-08','E-09']);});
test('transition table has no empty cell',()=>{for(const state of ['pending','accepted','revoked','expired'] as const){for(const event of ['accept','revoke','expire'] as const){assert.ok(TRANSITIONS[state][event],`${state}/${event}`);}}});
